# version: 0.013

# Builder stage
FROM node:20 as builder

WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx

# Copy Nginx configuration
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

RUN ls 

# Copy built files from the builder stage to Nginx
COPY --from=builder /app/dist /usr/share/nginx/html
