version: "3"
services:
  mongodb:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
    networks:
     - dock_mern
  api:
    build:
      dockerfile: dockerfile
      context: "./backend"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - dock_mern
  client:
    build:
      dockerfile: dockerfile
      context: "./client"
    volumes:
      - ./client:/app
    networks:
      - dock_mern
  nginx:
    depends_on:
      - api
      - chatf
      - client
    restart: always
    build:
      dockerfile: dockerfile
      context: "./nginx"
    ports:
      - 3050:80
    networks:
      - dock_mern
  chatf:
    build:
      dockerfile: dockerfile
      context: "./chat_feature"
    volumes:
      - ./chat_feature:/chat
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - dock_mern
volumes:
  mongodb_data:
networks:
  dock_mern: